--- 
- hosts: localhost
  tasks:
    - yum:
        name: "{{ item }}"
        state: present
      loop:
        - "@Development Tools"
        - bash-completion
        - bash-completion-extras
        - gcc
        - libcurl-devel
        - libxml2-devel gcc
        - nano
        - nss-devel
        - openldap-devel
        - openssl-devel
        - ovirt-engine-sdk-python
        - pygobject2
        - python-devel
        - python-lxml
        - python-pip
        - python-setuptools
        - python27-python-devel
        - python33-python-devel
        - rpm-build
        - vim
        - wget
      when: ansible_os_family == "RedHat"

  - pip:
      name:
        - python-networkmanager
        - python-ldap
        - pycurl
        - ovirt-engine-sdk-python
        - openldap
        - networkmanager-glib
        - network-manager
        - dbus-python
