---
# tasks file for iac-ansible-awx
#- name: Configurando repositorio PostgreSQL
#  yum:
#    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-latest-x86_64/pgdg-centos10-10-2.noarch.rpm
#    state: present
#  register: repo_postgres

- name: Instalar PostgreSQL
  yum: name={{ item }} state=latest
  with_items:
          - postgresql10-server
          - postgresql10-contrib 
          - postgresql10-libs
#  when: repo_installed|success 
    
- name: Instalar pacotes de pré-requisitos
  yum: name={{ item }} state=latest
  with_items:
          - epel-release
  register: epel_installed
    
- name: Instalar Dependencias
  yum: name={{ item }} state=latest
  with_items:
          - rabbitmq-server
          - wget
          - memcached
          - nginx
          - ansible
  when: epel_installed|success

- name: Adicionando o repositorio do AWX
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/mrmeee/awx/repo/epel-7/mrmeee-awx-epel-7.repo
    dest: /etc/yum.repos.d/awx-rpm.repo
    validate_certs: no
  register: repo_awx

- name: Instalar AWX
  yum: name=awx state=latest
  when: repo_awx|success
...
